- Improved wrappers a bit more - Abbreviated the names of some variables - Added 'gentoo' wrapper

diff --git a/plugins/service_file/wrappers/default.in b/plugins/service_file/wrappers/default.in
--- a/plugins/service_file/wrappers/default.in
+++ b/plugins/service_file/wrappers/default.in
@@ -1,9 +1,9 @@
 #!/bin/sh
 
 eval "
-${COMMAND}()
+${CMD}()
 {
-	echo \"${SERVICE}: command ${COMMAND} not found.\"
+	echo \"${SERVICE}: command ${CMD} not found.\"
 	return 1
 }
 "
@@ -11,7 +11,7 @@ ${COMMAND}()
 ireg()
 {
 	[ -n "${2}" ] && export SERVICE="${2}"
-	iregister "${1}" || exit 1
+	iregister "${1}" || exit ${?}
 }
 
 is_service()
@@ -24,6 +24,6 @@ is_service()
 }
 
 export PATH="@LIB_INSTALL_DIR@/ibin:${PATH}"
-source "${SERVICE_FILE}"
+source "${SFILE}" || exit ${?}
 
-${COMMAND}
+${CMD}
