- Added 'runlevel' wrapper - Added ireg func. to 'default' wrapper - Improved installation of wrappers

diff --git a/plugins/service_file/wrappers/default b/plugins/service_file/wrappers/default
--- a/plugins/service_file/wrappers/default
+++ b/plugins/service_file/wrappers/default
@@ -1,11 +1,20 @@
 #!/bin/sh
 
-eval "${COMMAND}() {
-	echo \"ERROR: ${SERVICE} command ${COMMAND} not found.\"
+eval "
+${COMMAND}()
+{
+	echo \"${SERVICE}: command ${COMMAND} not found.\"
 	return 1
-}"
+}
+"
 
-export PATH="/lib/ibin:${PATH}"
+ireg()
+{
+	[ -n "${2}" ] && export SERVICE="${2}"
+	iregister "${1}" || exit 1
+}
+
+export PATH="@LIB_INSTALL_DIR@/ibin:${PATH}"
 source "${SERVICE_FILE}"
 
 ${COMMAND}
